# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - clbo-joto-github-microservice

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_52fa185923b448129c8ac38531e17db6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a87117c2eff34b32868c34a2385fcabd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_52fa185923b448129c8ac38531e17db6 }}/clbo-github-microservice:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'clbo-joto-github-microservice'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9818c482d94f4d55885562b7475fad70 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_52fa185923b448129c8ac38531e17db6 }}/clbo-github-microservice:${{ github.sha }}'